#define GAME_RENDER_DEBUG_OUTPUT 0
#define GAME_RENDER_SKELETON_NODES 0
#define GAME_DEBUG_PRINTING 1
#define NO_PROFILING
#define GAME_OUT_OF_MEMORY_ASSERTION 0
#define GAME_BREAK_ON_ERROR_LOG 1

#define DLMALLOC_DEBUG_CHECKS 1